#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# mkdir -p constant/triSurface

cp ../1.model_Mhead/scale0/*.stl constant/triSurface

runApplication blockMesh

    runApplication surfaceFeatureExtract
    runApplication decomposePar
    runApplication mpirun -np `getNumberOfProcessors` --hostfile system/hosts snappyHexMesh -overwrite -parallel
    #runApplication mpirun -np `getNumberOfProcessors` snappyHexMesh -overwrite -parallel
    #runParallel snappyHexMesh -dict system/snappyHexMeshDict -overwrite
    runApplication reconstructParMesh -mergeTol 1e-12 -constant
    #paraFoam -builtin -touch    
    rm -rf processor* > /dev/null 2>&1

#runApplication surfaceFeatureExtract

runApplication snappyHexMesh -overwrite

# Restore initial fields
restore0Dir

runApplication splitMeshRegions -cellZones -overwrite

## Remove fluid fields from solid regions (important for post-processing)
#for region in $(foamListRegions solid)
#do
#    rm -f 0/"$region"/{nut,alphat,epsilon,k,U,p_rgh}
#    rm -f processor*/0/"$region"/{nut,alphat,epsilon,k,U,p_rgh}
#done
#
#for region in $(foamListRegions)
#do
#    runApplication -s "$region" changeDictionary -region "$region"
#done
#
## Run on single processor
#runApplication $(getApplication)
#
#echo
#echo "Use paraFoam -touch-all to create files for paraview post-processing"
#echo

#------------------------------------------------------------------------------
